//Pins
#define STEPPER_IN1 19
#define STEPPER_IN2 18
#define STEPPER_IN3 5
#define STEPPER_IN4 17
#define STEPPER_LIMSW_X 6
#define TEMPERATURE_SENSOR 4
#define DISPLAY_I2C_SDA 25
#define DISPLAY_I2C_SCL 26

//Constants
#define STEPS_PER_REVOLUTION 2038
#define MAX_POSITION 1000
#define CONFIG_SAVE_TIMEOUT 5000
#define DISPLAY_ROTATION_TIMEOUT 3000